language: go
go:
  - 1.1
  - 1.2
  - tip
script:
  - go test -covermode=count -coverprofile=profile.cov
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
